# docker version 3 example

version: "3.1"

services:
  tor:
    image: goldy/tor-hidden-service
    build: .
    links:
      - hello
      - world
      - again
    environment:
        # Set mapping ports
        HELLO_PORTS: 80:80,800:80,8888:80

        WORLD_PORTS: 8000:80

        AGAIN_PORTS: 88:80

        # hello and again will share the same onion_adress
        AGAIN_SERVICE_NAME: foo
        HELLO_SERVICE_NAME: foo

    # Keep keys in volumes
    volumes:
      - tor-keys:/var/lib/tor/hidden_service/

    # Set secret for key, use the same name as the service
    secrets:
      - source: foo
        target: foo
        mode: 0400

  hello:
    image: tutum/hello-world
    hostname: hello

  world:
    image: tutum/hello-world
    hostname: world

  again:
    image: tutum/hello-world
    hostname: again

volumes:
    tor-keys:
        driver: local

secrets:
    foo:
        file: ./foo_private_key
